version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  spring-boot-app:
    build: .
    container_name: spring-boot-container
    ports:
      - "4308:4308"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/storage
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123123
    depends_on:
      - postgres

volumes:
  postgres-data: