version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    command: server --console-address ":9090" /data/
    ports:
      - "9090:9090"
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    volumes:
      - minio-storage:/data

  spring-boot-app:
    build: .
    container_name: spring-boot-container
    env_file:
      - .env
    ports:
      - "4308:4308"
    depends_on:
      - postgres
      - minio

volumes:
  postgres-data:
  minio-storage: